---
name: Release
run-name: ${{ gitea.actor }} is releasing ${{ gitea.repository }}
on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: debian12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup ssh
        run: |
          mkdir ~/.ssh && chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "Host *
              StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/id_ed25519 ~/.ssh/config
      - name: Copy repository contents to remote server
        run: "scp ./* ${{ vars.SSH_REMOTE_USER }}@${{ vars.SSH_REMOTE_HOST }}:/kennzeichenkarte.de/httpdocs/"
